version: 2

project_name: gilly

builds:
  - skip: true

archives:
  - id: meta
    formats: [tar.gz]
    meta: true
    name_template: "{{ .ProjectName }}_{{ .Version }}"
    files:
      - gleam.toml
      - manifest.toml
      - src/**/*
      - test/**/*
      - LICENSE*
      - README*

checksum:
  name_template: "checksums.txt"

publishers:
  - name: Hex
    # Use a custom publish command since goreleaser doesn't have built-in support for publishing to Hex.
    cmd: hack/gleam_publish.sh {{ .ArtifactPath }}
    env:
      - HEXPM_API_KEY={{ .Env.HEXPM_API_KEY }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
