name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: erlef/setup-beam@v1
        with:
          otp-version: "28"
          gleam-version: "1.15.2"
          rebar3-version: "3"

      - run: gleam deps download

      - run: gleam build

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: nightly
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/attest@v4
        with:
          subject-checksums: ./dist/checksums.txt
